'use client'

import {
  ArrowLeft,
  DatabaseZap,
  FileWarning,
  RefreshCw,
  ShieldCheck,
} from 'lucide-react'
import Link from 'next/link'
import { useCallback, useEffect, useState } from 'react'
import { CompareAnalyzer, SingleAnalyzer } from '@/components/analyzer'

type GateState = 'checking' | 'ready' | 'unavailable'

export function AnalyzerAvailabilityGate({
  mode,
}: {
  mode: 'single' | 'compare'
}) {
  const [state, setState] = useState<GateState>('checking')
  const [checkedAt, setCheckedAt] = useState<string>('')

  const checkAvailability = useCallback(async () => {
    setState('checking')

    try {
      const [routesResponse, modulesResponse] = await Promise.all([
        fetch('/data/routes.json', {
          cache: 'no-store',
        }),
        fetch('/data/modules.data', {
          method: 'HEAD',
          cache: 'no-store',
        }),
      ])

      setCheckedAt(new Date().toLocaleTimeString())

      if (routesResponse.ok && modulesResponse.ok) {
        setState('ready')
        return
      }

      setState('unavailable')
    } catch {
      setCheckedAt(new Date().toLocaleTimeString())
      setState('unavailable')
    }
  }, [])

  useEffect(() => {
    void checkAvailability()
  }, [checkAvailability])

  if (state === 'ready') {
    return mode === 'single' ? <SingleAnalyzer /> : <CompareAnalyzer />
  }

  if (state === 'checking') {
    return (
      <main className="flex min-h-screen items-center justify-center p-4 sm:p-6">
        <div className="nf-glass-strong w-full max-w-3xl rounded-[30px] p-6 sm:p-8">
          <div className="flex items-center gap-4">
            <div className="nf-skeleton size-12 rounded-[18px]" />
            <div className="flex-1">
              <div className="nf-skeleton h-4 w-40 rounded-full" />
              <div className="nf-skeleton mt-3 h-3 w-64 max-w-full rounded-full" />
            </div>
          </div>
          <div className="mt-8 grid gap-3 sm:grid-cols-3">
            <div className="nf-skeleton h-24 rounded-[20px]" />
            <div className="nf-skeleton h-24 rounded-[20px]" />
            <div className="nf-skeleton h-24 rounded-[20px]" />
          </div>
        </div>
      </main>
    )
  }

  return (
    <main className="relative flex min-h-screen items-center justify-center overflow-hidden p-4 sm:p-6">
      <div className="pointer-events-none absolute inset-0 nf-grid opacity-25" />
      <div className="pointer-events-none absolute -left-24 top-10 size-80 rounded-full bg-[#74317a]/15 blur-3xl" />
      <div className="pointer-events-none absolute -right-24 bottom-10 size-80 rounded-full bg-[#d7afd7]/20 blur-3xl" />

      <section className="nf-glass-strong relative w-full max-w-4xl overflow-hidden rounded-[32px] p-6 sm:p-8 lg:p-10">
        <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
          <div className="max-w-2xl">
            <div className="mb-5 flex size-12 items-center justify-center rounded-[18px] bg-primary/10 text-primary">
              <DatabaseZap className="size-5" />
            </div>
            <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary/70">
              Bundle Analyzer · Data source
            </p>
            <h1 className="mt-2 text-2xl font-semibold tracking-[-0.04em] sm:text-3xl">
              No bundle snapshot is loaded.
            </h1>
            <p className="mt-3 text-sm leading-7 text-muted-foreground">
              The analyzer UI is available, but a standalone Vercel deployment
              does not include the generated bundle-analysis files by default.
              The analyzer expects a snapshot under <code>/data</code> before it
              can render modules, routes and import chains.
            </p>
          </div>

          <div className="rounded-full border border-border bg-background/50 px-3 py-1.5 font-mono text-[10px] text-muted-foreground">
            {checkedAt ? `checked ${checkedAt}` : 'source unavailable'}
          </div>
        </div>

        <div className="mt-8 grid gap-3 md:grid-cols-3">
          {[
            {
              icon: FileWarning,
              title: 'routes.json',
              detail: 'Route index generated by a bundle-analysis session.',
            },
            {
              icon: DatabaseZap,
              title: 'modules.data',
              detail: 'Binary module graph used by the interactive treemap.',
            },
            {
              icon: ShieldCheck,
              title: 'analyze.data',
              detail: 'Per-route bundle details used by the analyzer views.',
            },
          ].map((item) => {
            const Icon = item.icon
            return (
              <div
                key={item.title}
                className="rounded-[22px] border border-border/70 bg-background/35 p-4"
              >
                <Icon className="size-4 text-primary" />
                <p className="mt-4 font-mono text-xs font-semibold">{item.title}</p>
                <p className="mt-2 text-xs leading-5 text-muted-foreground">
                  {item.detail}
                </p>
              </div>
            )
          })}
        </div>

        <div className="mt-8 flex flex-wrap gap-2.5">
          <Link
            href="/"
            className="inline-flex min-h-10 items-center gap-2 rounded-full bg-primary px-4 text-sm font-medium text-primary-foreground"
          >
            <ArrowLeft className="size-4" />
            Back to Next Forge
          </Link>
          <button
            onClick={() => void checkAvailability()}
            className="inline-flex min-h-10 items-center gap-2 rounded-full border border-border bg-background/55 px-4 text-sm font-medium transition-colors hover:bg-muted"
          >
            <RefreshCw className="size-4" />
            Retry data source
          </button>
        </div>

        <p className="mt-5 text-xs leading-5 text-muted-foreground">
          This prevents the standalone console from failing with
          <code className="mx-1 rounded bg-muted px-1.5 py-0.5 font-mono">/data/modules.data: 404</code>
          while preserving the original analyzer whenever generated data is present.
        </p>
      </section>
    </main>
  )
}
